---
# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github:
patreon:  # Replace with a single Patreon username
open_collective:  # Replace with a single Open Collective username
ko_fi:  # Replace with a single Ko-fi username
# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
tidelift:
# Replace with a single Community Bridge project-name e.g., cloud-foundry
community_bridge:
liberapay:  # Replace with a single Liberapay username
issuehunt:  # Replace with a single IssueHunt username
# Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
lfx_crowdfunding:
polar:  # Replace with a single Polar username
buy_me_a_coffee: jromero132
thanks_dev:  # Replace with a single thanks.dev username
custom:  # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
